shortcuts:
  copyright: 'Copyright (c) 2020 by Idle-Corp, all rights reserved.'
  website_url: 'https://idle-corp.com'
  website_name: 'Idle-Corp'
  cc_license: 'CC-BY-SA-4.0'
  replace: 'Test with {} and {}'
  alias: 'test alias replacement with format {test}'
  do_not_remove_s: 'This is a test'
  do_not_remove_f: 'This is a test {} {} {a} {b}'
  tab_bnw: 'tab_bnw_imported'
  tab_color: 'tab_colour_imported'
  custom_permutation: 'custom_permutated'

images:
  logo: 'resources/images/logo.png'
  favicon: 'resources/images/favicon.png'
  do_not_remove_p: 'This is a test'
  do_not_remove_f: 'This is a test {} {} {a} {b}'
  custom_pict: 'custom_pict.png'
  sch: 'sch.png'
  vuln: 'vuln.png'
  image: 'image.img'
  whatever_picture: 'whatever_picture.pic'
  image.png: 'image.png.png'