logging:
  level: "INFO"
  path: "log/bootstraparse.log"
  log_to_console: true


parsing:
  includes: true
  preparse: true
  parse: true


export:
  intermediate_files: true
  type: "html"
  force_rewrite: true
