# This workflow will install Python dependencies, and deploy the application to GitHub Pages.

name: Python application

on:
  push:
    branches: [ main, release ]
  pull_request:
    branches: [ main, release ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Build the application
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          python -m bootstraparse "example_userfiles" "docs"
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs